Wrench but better
J3fftw1/LiteXpansion pull request #67
Opened 2020-09-14 22:38 UTC by NCBPFluffyBear

## Short Description
Added wrench that instantly breaks machines. On a server with `need-wrench-to-break-machines` set to false, the wrench has a 0% failure chance and breaking machines without the wrench will drop the machine. On a server with `need-wrench-to-break-machines` set to true, the wrench has a `wrench-failure-chance` (default of 0.3) to fail when breaking machines, and if a machine is broken without a wrench, it will drop a machine block. Wrench takes default durability damage when used, can be used by left and right clicking machines, and only works in main hand.

*Machines include generators but do not include capacitors or cargo nodes
https://streamable.com/rcca8k (This is a new video)

**This changes the old wrench by simply calling a block break event for cargo, which is simpler and more efficient.

## Additions/Changes/Removals
- Added wrench class
- Added wrench item lore
- Added wrench registering
- Added `need-wrench-to-break-machines` config option (true for new servers, false for existing servers)
- Added `wrench-failure-chance` config option (0.0 for new servers, 0.0 for existing servers)
- Added block break event that turns machines and generators into machine blocks when broken without wrench

## Related Issues
#52 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2020-09-14 23:13 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/items/Wrench.java
> +            null, Items.CARBON_PLATE, null
Default wrench should be just copper

2020-09-14 23:13 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/items/Wrench.java
> +    @EventHandler
We still have an event class

2020-09-15 04:26 UTC, NCBPFluffyBear commented on src/main/java/dev/j3fftw/litexpansion/items/Wrench.java
> +            null, Items.CARBON_PLATE, null
whoopsies forgot to change that

2020-09-27 19:24 UTC, J3fftw1 commented
Add research

2020-10-04 17:56 UTC, J3fftw1 commented
conflicts

2020-10-04 17:57 UTC, J3fftw1 requested changes

2020-10-04 17:57 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/Events.java
> +            } else if (sfBlock != null && (sfBlock.getID().startsWith("CARGO_NODE")
move && to new line

2020-10-04 17:57 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/Events.java
> +    public static void wrenchBlock(Player p, Block block, boolean fail, boolean byInteract) {
little inconsistent here uses Player p and Block b

2020-10-08 11:32 UTC, merged