More solar panels
J3fftw1/LiteXpansion pull request #79
Opened 2020-09-25 19:49 UTC by Mooy1

## Short Description
Added basic, lv, mv, hv solar panels in a new class. changed recipes and outputs of advanced panels.

## Additions/Changes/Removals
basic panel 10 j/s 10k storage
low voltage panel 100 j/s 25k storage
medium voltage panel 200 j/s 50k storage
high voltage panel 400 j/s 100k storage

advanced panel recipe now requires a high voltage panel

## Related Issues
none

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2020-09-25 20:11 UTC, Mooy1 commented
Everything works ingame :)

2020-09-25 20:24 UTC, J3fftw1 requested changes

2020-09-25 20:24 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/ItemSetup.java
> +import dev.j3fftw.litexpansion.machine.*;
never wildcard import

2020-09-25 20:24 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/Items.java
> +        "&6Only works during the day",
no need to state that it works during the day since
euhm 
its a solar panel
same for the others

2020-09-25 20:24 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/machine/BasicSolarPanel.java
> +    public BasicSolarPanel(Basic type) {
rename basic to type

2020-09-25 20:24 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/machine/BasicSolarPanel.java
> +        if (world.getEnvironment() == World.Environment.NETHER) return this.type.getDayGenerationRate();
return 0 here

2020-09-26 16:33 UTC, J3fftw1 requested changes

2020-09-26 16:33 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/machine/AdvancedSolarPanel.java
> +    public static int HIGH_VOLTAGE_STORAGE = 100_000;
why is this here

2020-10-19 15:35 UTC, J3fftw1 commented
I dont think we need more solar panels
sorry for all the work you put into it but i have to close it

2020-10-19 15:35 UTC, closed without merging